# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: quangtrong.news::lang.menu.import
    modelClass: Quangtrong\News\Models\PostsImport
    list: $/quangtrong/news/models/postsimport/columns.yaml
    redirect: quangtrong/news/posts
    permissions: quangtrong.news.import_export

export:
    title: quangtrong.news::lang.menu.export
    modelClass: Quangtrong\News\Models\PostsExport
    list: $/quangtrong/news/models/postsexport/columns.yaml
    redirect: quangtrong/news/posts
    permissions: quangtrong.news.import_export
    filename: posts.csv
