# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    status_active:
        label: quangtrong.news::lang.form.status_active
        type: checkbox
        conditions: status = 1

    status_unsubscribed:
        label: quangtrong.news::lang.form.status_unsubscribed
        type: checkbox
        conditions: status = 2

    categories:
        label: quangtrong.news::lang.form.category
        modelClass: Quangtrong\News\Models\Categories
        nameFrom: name
        scope: FilterCategories

    statistics:
        label: quangtrong.news::lang.stat.mail
        type: numberrange
        conditions: statistics >= ':min' and statistics <= ':max'

    created_date:
        label: quangtrong.news::lang.form.created
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    updated_date:
        label: quangtrong.news::lang.form.updated
        type: daterange
        conditions: updated_at >= ':after' AND updated_at <= ':before'
